#gionee liujiang 2013-10-17 add for akm8963 pdc start
ifeq ($(GN_Q_BSP_AKM8963_PDC_SUPPORT), yes)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
AKMD_DEVICE_TYPE = 8963
# Define Device
ifeq ($(AKMD_DEVICE_TYPE), 8975)
DEVICE_STRING=8975
else ifeq ($(AKMD_DEVICE_TYPE), 8963)
DEVICE_STRING=8963
else ifeq ($(AKMD_DEVICE_TYPE), 9912)
DEVICE_STRING=09912
else ifeq ($(AKMD_DEVICE_TYPE), 9911)
DEVICE_STRING=09911
else
$(error AKMD_DEVICE_TYPE is not defined)
endif

LOCAL_PREBUILT_LIBS := libSmartCompass/libAKM_WO6D.a
LOCAL_MODULE_TAGS := optional
include $(BUILD_MULTI_PREBUILT)

include $(CLEAR_VARS)

# Define Device
ifeq ($(AKMD_DEVICE_TYPE), 8975)
DEVICE_STRING=8975
LOCAL_CFLAGS := -DAKMD_AK8975
else ifeq ($(AKMD_DEVICE_TYPE), 8963)
DEVICE_STRING=8963
LOCAL_CFLAGS := -DAKMD_AK8963
else ifeq ($(AKMD_DEVICE_TYPE), 9912)
DEVICE_STRING=09912
LOCAL_CFLAGS := -DAKMD_AK09912
else ifeq ($(AKMD_DEVICE_TYPE), 9911)
DEVICE_STRING=09911
LOCAL_CFLAGS := -DAKMD_AK09911
else
$(error AKMD_DEVICE_TYPE is not defined)
endif


LOCAL_C_INCLUDES += \
	$(LOCAL_PATH) \
	$(LOCAL_PATH)/libSmartCompass

LOCAL_SRC_FILES += \
	AKMD_APIs.c \
	FileIO.c \
	Measure.c

LOCAL_CFLAGS += -DAKSC_DISABLE_D6D

## Enable ALOGE
#LOCAL_CFLAGS += -UNDEBUG
#LOCAL_CFLAGS += -DENABLE_AKMDEBUG=1
#LOCAL_CFLAGS += -DAKM_LOG_ENABLE

LOCAL_WHOLE_STATIC_LIBRARIES += libAKM_WO6D
LOCAL_SHARED_LIBRARIES += liblog
LOCAL_MODULE:=libAKM8963
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)
LOCAL_PRELINK_MODULE := false
#PRODUCT_COPY_FILES += $(LOCAL_PATH)/pdc.txt:data/misc/sensors/pdc.txt
include $(BUILD_SHARED_LIBRARY)
endif
#gionee liujiang 2013-10-17 add for akm8963 pdc end

